# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build & test w local reg.

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Set up JDK 21
      uses: actions/setup-java@v6
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    - name: Install local registry
      run: |
        /bin/bash -c "$(curl -fsSL https://data.fairdatapipeline.org/static/localregistry.sh)"
        ~/.fair/registry/scripts/start_fair_registry
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
        export REGTOKEN=`cat ~/.fair/registry/token`
        export LOCALREG=FRESHASADAISY
        ./gradlew build
    - uses: codecov/codecov-action@v7
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./api/build/reports/jacoco/test/jacocoTestReport.xml,./dataregistry/build/reports/jacoco/test/jacocoTestReport.xml
